"""Initial migration.

Revision ID: 93abb6271280
Revises: 
Create Date: 2023-06-26 04:18:51.972744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93abb6271280'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code_path', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_column('qr_code_path')

    # ### end Alembic commands ###
