"""Initial migration

Revision ID: baace1097ed8
Revises: 
Create Date: 2023-06-27 15:23:33.444431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baace1097ed8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_column('qr_code_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code_path', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
